/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4Fga6ypEJ4o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function FeaturedSection() {
  return (
		<section className="w-full py-6 xl:py-12">
			<div className="container space-y-12 px-4 md:px-6">
				<div className="flex flex-col items-center justify-center space-y-4 text-center">
					<div className="space-y-2">
						<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
							Featured Projects
						</h2>
						<p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
							Check out some of our recent web consulting
							projects that showcase our expertise in
							design, development, and strategy.
						</p>
					</div>
				</div>
				<div className="mx-auto grid gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
					<div className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 hover:shadow-xl">
						<Link
							href="#"
							className="absolute inset-0 z-10"
							prefetch={false}
						>
							<span className="sr-only">View Project</span>
						</Link>
						<img
							src="/placeholder.svg"
							width={500}
							height={300}
							alt="Project 1"
							className="h-64 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
						/>
						<div className="bg-background p-4">
							<h3 className="text-lg font-bold">
								Project 1
							</h3>
							<p className="text-sm text-muted-foreground">
								A modern and responsive website for a
								leading web consulting agency.
							</p>
						</div>
					</div>
					<div className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 hover:shadow-xl">
						<Link
							href="#"
							className="absolute inset-0 z-10"
							prefetch={false}
						>
							<span className="sr-only">View Project</span>
						</Link>
						<img
							src="/placeholder.svg"
							width={500}
							height={300}
							alt="Project 2"
							className="h-64 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
						/>
						<div className="bg-background p-4">
							<h3 className="text-lg font-bold">
								Project 2
							</h3>
							<p className="text-sm text-muted-foreground">
								A custom web application for a SaaS startup,
								built with a focus on user experience and
								scalability.
							</p>
						</div>
					</div>
					<div className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 hover:shadow-xl">
						<Link
							href="#"
							className="absolute inset-0 z-10"
							prefetch={false}
						>
							<span className="sr-only">View Project</span>
						</Link>
						<img
							src="/placeholder.svg"
							width={500}
							height={300}
							alt="Project 3"
							className="h-64 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
						/>
						<div className="bg-background p-4">
							<h3 className="text-lg font-bold">
								Project 3
							</h3>
							<p className="text-sm text-muted-foreground">
								A visually stunning website for a luxury
								fashion brand, designed to showcase their
								latest collections.
							</p>
						</div>
					</div>
					<div className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 hover:shadow-xl">
						<Link
							href="#"
							className="absolute inset-0 z-10"
							prefetch={false}
						>
							<span className="sr-only">View Project</span>
						</Link>
						<img
							src="/placeholder.svg"
							width={500}
							height={300}
							alt="Project 4"
							className="h-64 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
						/>
						<div className="bg-background p-4">
							<h3 className="text-lg font-bold">
								Project 4
							</h3>
							<p className="text-sm text-muted-foreground">
								A mobile-first e-commerce website for a
								sustainable clothing brand, optimized for
								conversion and user experience.
							</p>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
