/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xRboTUeDmpr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { NavigationMenu, NavigationMenuList, NavigationMenuLink, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent } from "@/components/ui/navigation-menu"

export function NavMenu() {
  return (
		<header className="flex h-20 w-full shrink-0 items-center">
			<Sheet>
				<SheetTrigger asChild>
					<Button
						variant="outline"
						size="icon"
						className="lg:hidden"
					>
						<MenuIcon className="h-6 w-6" />
						<span className="sr-only">
							Toggle navigation menu
						</span>
					</Button>
				</SheetTrigger>
				<SheetContent side="left">
					<Link
						href="#"
						className="flex items-center gap-2"
						prefetch={false}
					>
						<MountainIcon className="h-6 w-6" />
						<span className="text-lg font-bold">
							Acme Inc
						</span>
					</Link>
					<div className="grid gap-4 py-6">
						<Link
							href="/"
							className="flex items-center gap-2 text-lg font-medium"
							prefetch={false}
						>
							Homepage
						</Link>
						<Link
							href="#"
							className="flex items-center gap-2 text-lg font-medium"
							prefetch={false}
						>
							About Us
						</Link>
						<Collapsible className="grid gap-4">
							<CollapsibleTrigger className="flex items-center gap-2 text-lg font-medium [&[data-state=open]>svg]:rotate-90">
								Services{" "}
								<ChevronRightIcon className="ml-auto h-5 w-5 transition-all" />
							</CollapsibleTrigger>
							<CollapsibleContent>
								<div className="-mx-6 grid gap-4 bg-muted p-6">
									<Link
										href="#"
										className="flex items-center gap-2 text-base font-medium"
										prefetch={false}
									>
										Web Development
									</Link>
									<Link
										href="#"
										className="flex items-center gap-2 text-base font-medium"
										prefetch={false}
									>
										SEO Optimization
									</Link>
									<Link
										href="#"
										className="flex items-center gap-2 text-base font-medium"
										prefetch={false}
									>
										E-Commerce Solutions
									</Link>
									<Link
										href="#"
										className="flex items-center gap-2 text-base font-medium"
										prefetch={false}
									>
										Mobile App Development
									</Link>
									<Link
										href="#"
										className="flex items-center gap-2 text-base font-medium"
										prefetch={false}
									>
										UI/UX Design
									</Link>
								</div>
							</CollapsibleContent>
						</Collapsible>
						<Link
							href="#"
							className="flex items-center gap-2 text-lg font-medium"
							prefetch={false}
						>
							Projects
						</Link>
						<Link
							href="#"
							className="flex items-center gap-2 text-lg font-medium"
							prefetch={false}
						>
							Testimonials
						</Link>
						<Link
							href="/blog"
							className="flex items-center gap-2 text-lg font-medium"
							prefetch={false}
						>
							Blog
						</Link>
						<Link
							href="#"
							className="flex items-center gap-2 text-lg font-medium"
							prefetch={false}
						>
							Contact Us
						</Link>
						<Link
							href="/schedule-consultation"
							prefetch={false}
							className="flex items-center gap-2 text-lg font-medium"
						>
							Schedule Consultation
						</Link>
					</div>
				</SheetContent>
			</Sheet>
			<div className="ml-auto hidden lg:flex">
				<NavigationMenu>
					<NavigationMenuList>
						<NavigationMenuLink asChild>
							<Link
								href="/"
								className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
								prefetch={false}
							>
								Homepage
							</Link>
						</NavigationMenuLink>
						<NavigationMenuLink asChild>
							<Link
								href="#"
								className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
								prefetch={false}
							>
								About Us
							</Link>
						</NavigationMenuLink>
						<NavigationMenuItem>
							<NavigationMenuTrigger>
								Services
							</NavigationMenuTrigger>
							<NavigationMenuContent>
								<div className="grid w-[400px] p-2">
									<NavigationMenuLink asChild>
										<Link
											href="#"
											className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
											prefetch={false}
										>
											Web Development
										</Link>
									</NavigationMenuLink>
									<NavigationMenuLink asChild>
										<Link
											href="#"
											className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
											prefetch={false}
										>
											SEO Optimization
										</Link>
									</NavigationMenuLink>
									<NavigationMenuLink asChild>
										<Link
											href="#"
											className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
											prefetch={false}
										>
											E-Commerce Solutions
										</Link>
									</NavigationMenuLink>
									<NavigationMenuLink asChild>
										<Link
											href="#"
											className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
											prefetch={false}
										>
											Mobile App Development
										</Link>
									</NavigationMenuLink>
									<NavigationMenuLink asChild>
										<Link
											href="#"
											className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
											prefetch={false}
										>
											UI/UX Design
										</Link>
									</NavigationMenuLink>
								</div>
							</NavigationMenuContent>
						</NavigationMenuItem>
						<NavigationMenuLink asChild>
							<Link
								href="#"
								className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
								prefetch={false}
							>
								Projects
							</Link>
						</NavigationMenuLink>
						<NavigationMenuLink asChild>
							<Link
								href="#"
								className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
								prefetch={false}
							>
								Testimonials
							</Link>
						</NavigationMenuLink>
						<NavigationMenuLink asChild>
							<Link
								href="/blog"
								className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
								prefetch={false}
							>
								Blog
							</Link>
						</NavigationMenuLink>
						<NavigationMenuLink asChild>
							<Link
								href="#"
								className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
								prefetch={false}
							>
								Contact Us
							</Link>
						</NavigationMenuLink>
						<NavigationMenuLink asChild>
							<Link
								href="/schedule-consultation"
								className="text-center inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Schedule Consultation
							</Link>
						</NavigationMenuLink>
					</NavigationMenuList>
				</NavigationMenu>
			</div>
		</header>
	);
}

function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function MenuIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
